steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/bankdash22/bankdash-back', '.' ]
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/bankdash22/bankdash-back"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'bankdash-back-app'
  - 'bankdash-back=gcr.io/bankdash22/bankdash-back:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=bankdash-cluster'