steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/bankdash22/bankdash-back', '.' ]
  dir: 'backend'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/bankdash-back-app'
  - 'my-container=gcr.io/bankdash22/bankdash-back'
images:
- 'gcr.io/bankdash22/bankdash-back'